### ISSUE TITLE
It doesn't auto-apply

### ISSUE THREAD

**Issue by allanmviana** [dumindu/night-owl#1] opened 2018-09-30 15:19 UTC
Just simple as that.
Everytime I close and run firefox I need to reapply the _theme_.

BTW, great theme, just love it.

**Comment by dumindu** [comment] 2018-09-30 16:54
addon version 0.3 or 0.3.2?

**Comment by allanmviana** [comment] 2018-09-30 19:14
0.3.2
Firefox 62.0.2
Windows 10

**Comment by dumindu** [comment] 2018-10-03 13:21
Unfortunately I can not check this on Windows env now a days. But I'll check this when I got a chance.

**Comment by allanmviana** [comment] 2018-10-03 16:08
Actually I just figured it out. The extesion won't auto-apply if you have [Firefox Color](https://color.firefox.com/)

**Comment by dumindu** [comment] 2018-10-14 14:13
Won't fix!

@allanmviana This is not a bug, this is expected behavior. They have created Firefox Color to replace any theme or customizations in the browser window with Firefox Color customizations. Btw if you are using Firefox Color, you can use [same colors of this theme](https://github.com/dumindu/night-owl/blob/master/app.js) via it :)

**Closed as completed by dumindu** 2018-10-14 14:13 UTC
Labels: wontfix
